- name: Elasticsearch Config test modify
  hosts: cli
  roles:
#    expand to all available parameters
    - { role: elasticsearch, es_instance_name: "ELS-CLUSTER-NODE-1", es_data_dirs: ["/opt/elasticsearch/data-1","/opt/elasticsearch/data-2"], es_log_dir: "/opt/elasticsearch/logs", es_user_id: 333, es_group_id: 333, es_config: {node.name: "ELS-CLUSTER-NODE-1", cluster.name: "custom-cluster", discovery.zen.ping.unicast.hosts: "localhost:9501", http.port: 9200, transport.tcp.port: 9501, node.data: true, node.master: true, bootstrap.memory_lock: true } }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 1g
 #   add a custom log4j file
    es_config_log4j2: "./files/logging/log4j2.properties.custom.j2"
    es_api_port: 9200
    es_max_threads: 3000
    es_plugins:
      - plugin: ingest-attachment
      - plugin: ingest-user-agent
